# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: productionpw

# Documentation: https://roots.io/trellis/docs/security/
vault_users:
  - name: "{{ admin_user }}"
    password: example_password
    salt: "generateme"

# Variables to accompany `group_vars/production/wordpress_sites.yml`
# Note: the site name (`sameday.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  sameday.com:
    env:
      db_password: example_dbpassword
      # Generate your keys here: https://roots.io/salts.html
      auth_key: "43YP[qj2+Ym[)CJ]7/_?n8c1lSZ?WK1anne65IBjYn;G)In6O/Nm])HY&E(&9ZSU"
      secure_auth_key: ".K6j_vIEq9bI4YLi(&{wz8p_`E.JzE[sc)3yQphD!Xd$PKM3Y|.b)>S_)z.4o2;E"
      logged_in_key: "v}G<28Vt>qLP*s;fh3]L/(C{`0UUAWN1,*>=e5RokOz6ynE32{*&t$=beH05[5tw"
      nonce_key: "o&9[*O@62Y0:K7ym-`a+WQHZ)C?aiXh9Q$GChP4Y4}RfaqCg&M}QMK)1<.E)6Bh="
      auth_salt: "[{n8imWqlhd>4urK[}B|7Hc}dv(1fk:msZoI(.RGI*IR@LuO0/$9TQD/iB:seipH"
      secure_auth_salt: "lqOPh|zkH@;aS/>65U*Lv[cTdx}Vu&hV>t}OnN+&6hf=CZ1<+sATZYOU5}{l59ay"
      logged_in_salt: "[ObS^oIerRMPCF#]zD2}N6W:Rh2&<9`{>7$.+I:r/Mm}*&e38:zKWE(xs!p]4khV"
      nonce_salt: "oVyFp5X*`[0!`VwlpQ&_O]!KDv9fMJihOLcqP#WcNeRNg,bgy&{-fLMM6@@@#_ju"
