ssmtp_package: ssmtp
ssmtp_auth_method: LOGIN
ssmtp_from_override: "Yes"
ssmtp_start_tls: "Yes"
ssmtp_tls: "Yes"
# ssmtp_revaliases:
#   - user: root
#     from: from@sameday.com
#     smtp_server: "{{ mail_smtp_server }}"
#   - user: "{{ admin_user }}"
#     from: from@sameday.com
#     smtp_server: "{{ mail_smtp_server }}"
#   - user: "{{ web_user }}"
#     from: from@sameday.com
#     smtp_server: "{{ mail_smtp_server }}"
